### ISSUE TITLE
nginx内存池

### ISSUE THREAD

**Issue by zhangchaichai** [Cstardust/My_ngx_mem_pool#1]
你好，可以发下博客地址吗？

**Comment by Cstardust** [comment]
xd抱歉啊。我这个github博客的配置还有些没搞好。因为最近要考试有些忙，最迟一周之后博客可以发出来😭。发出来之后告诉你😭

**Comment by Cstardust** [comment]
> 

xd抱歉啊。我这个github博客的配置还有些没搞好。因为最近要考试有些忙，最迟一周之后博客可以发出来😭。发出来之后告诉你😭

**Comment by Cstardust** [comment]
> 你好，可以发下博客地址吗？

xd抱歉啊。我这个github博客的配置还有些没搞好。因为最近要考试有些忙，最迟一周之后博客可以发出来😭。发出来之后告诉你😭

**Comment by Cstardust** [comment]
> 你好，可以发下博客地址吗？

[地址](https://cstardust.github.io/2022/04/22/nginx%E5%86%85%E5%AD%98%E6%B1%A0/)
评论一下呗xd 或者觉得我写的哪里不对提点建议什么的
